name: CI Pipeline for Cat vs Dog Classifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Authenticate DVC with Google Drive
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive-credentials.json
          dvc remote modify gdrive_remote gdrive_use_service_account true
          dvc remote modify gdrive_remote gdrive_service_account_json gdrive-credentials.json

      - name: Pull Data from DVC
        run: dvc pull || echo "⚠️ DVC pull failed! Please check logs."

      - name: Run DVC Pipeline
        run: dvc repro || echo "⚠️ DVC pipeline execution failed!"

      - name: Evaluate Model
        run: python -m models.evaluate || echo "⚠️ Model evaluation failed!"
