name: CI Pipeline for Cat vs Dog Classifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Authenticate DVC with Google Drive
        run: |
          # 1. Write service account JSON to a file
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > gdrive-credentials.json

          # 2. Tell DVC to use a service account (no user login)
          dvc remote modify gdrive_remote gdrive_use_service_account true

          # 3. Store the key path in local config (avoid 'extra keys not allowed')
          dvc remote modify gdrive_remote --local gdrive_service_account_json gdrive-credentials.json

      - name: Pull Data from DVC
        run: dvc pull

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Evaluate Model
        run: python -m models.evaluate
