name: CI Pipeline for Cat vs Dog Classifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Configure DVC
        run: |
          dvc remote modify gdrive_remote url "gdrive://${{ secrets.GDRIVE_FOLDER_ID }}/cat-vs-dog-classifier"
          dvc remote modify gdrive_remote gdrive_client_id "${{ secrets.GDRIVE_CLIENT_ID }}"
          dvc remote modify gdrive_remote gdrive_client_secret "${{ secrets.GDRIVE_CLIENT_SECRET }}"
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

      - name: Pull Data from DVC
        run: dvc pull

      - name: Run DVC Pipeline
        run: dvc repro

      - name: Evaluate Model
        run: python -m models.evaluate
