name: CI Pipeline for Cat vs Dog Classifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code จาก repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. ติดตั้ง dependencies และ DVC (พร้อมรองรับ Google Drive)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gdrive]"

      # 4. กำหนดค่า DVC remote สำหรับ Google Drive
      - name: Configure DVC remote for Google Drive
        run: |
          dvc remote modify gdrive_remote url "gdrive://${{ secrets.GDRIVE_FOLDER_ID }}/cat-vs-dog-classifier"
          dvc remote modify gdrive_remote gdrive_client_id "${{ secrets.GDRIVE_CLIENT_ID }}"
          dvc remote modify gdrive_remote gdrive_client_secret "${{ secrets.GDRIVE_CLIENT_SECRET }}"
        env:
          # กำหนด Environment variable เพื่อให้สามารถเข้าถึง secrets ได้
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

      # 5. ดึงข้อมูลจาก DVC remote
      - name: DVC Pull Data
        run: dvc pull

      # 6. รัน DVC pipeline (prepare_data, train, evaluate)
      - name: Run DVC Pipeline
        run: dvc repro

      # 7. รัน evaluation script (เพื่อทดสอบโมเดล)
      - name: Run Evaluation
        run: python -m models.evaluate

      # 8. แสดงผล metrics (ถ้ามีการตั้งค่า metrics ใน dvc.yaml)
      - name: Show DVC Metrics
        run: dvc metrics show
